import { Navbar, Sidebar } from "@/components/ui"
import { SidebarProvider } from "@/contexts"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <SidebarProvider>
          <Navbar />
          {/* dashboard wrapper */}
          <section className="admin__layout">
            <Sidebar />
            <section className="min-h-screen p-5 w-full">{children}</section>
          </section>
        </SidebarProvider>
      </body>
    </html>
  )
}
