import type { ComponentProps, HTMLInputTypeAttribute, ReactNode } from "react"
import type { FieldErrors, Path, UseFormRegister } from "react-hook-form"
import type { IconType } from "react-icons"

export type ProvidersProps = {
  children: ReactNode
}

export type LocationSearchQuery = {
  query: string
}

export type UserProps = {
  id: string
  firstName: string
  lastName: string
  email: string
  conferences: string[]
  emailVerified: boolean
}

export type AttendeeProps = {
  attendee: {
    id: string
    firstName: string
    lastName: string
    email: string
  }
  membershipType: string
  paymentStatus: "PAYMENT_SUCCESSFUL"
}

export type NewsProps = {
  id: string
  title: string
  desc: string
  thumbnailUrl: string
  author: string

}

export type ExcoProps = {
  name: string
  position: string
  imageUrl: string
}

export type EditMemberProfileProps = {
  firstName: string
  lastName: string
  phoneNumber: string
  email: string
  status: "active" | "inactive" // get status...
  position?: string
}

export type ConferenceCardProps = {
  thumbnailUrl: string
  title: string
  content: string
  date: string // Date
  location: string
}

export type CourseCardProps = {
  thumbnailUrl: string
  title: string
  duration: string
  level: string // "Beginner" | "Intermediate" | "Advanced"
  rating: number
  author: {
    imageUrl: string
    name: string
  }
}

export type ConferenceRegisterProps = {
  attendeeId: string
  emailAddress: string
  membershipType: "TIMSANITE" | "IOTB" | "OTHERS" | ""
  paymentStatus: "PAYMENT_SUCCESSFUL" | "PAYMENT_PENDING" | ""
}

export type DashboardCardProps = {
  Icon: IconType
  total: number
  title: string
}

export type StatusCardProps = {
  title: string
  approved: number
  pending: number
  active: number
  url: string
}

export type TiletCardProps = {
  thumbnailUrl: string
  title: string
  text: string
  url: string
}

export type DonationProps = {
  name: string
  email: string
  amount: number | null
  paymentOption?: string
}

export type HeroCarouselCardProps = {
  thumbnailUrl: string
  title: string
}

export type AnnualDueFormProps = {
  chapterName: string
  email: string
  amount: string // number ?
}

export type BookCardProps = {
  imageUrl: string
  title: string
  rating: number
  author: string
}

export type ExcoCardProps = {
  name: string
  imageUrl: string
  position: string
}

export type LoginProps = {
  email: string
  password: string
}

export type VerifyEmailProps = {
  email: string
}

export type ResetPasswordProps = {
  oldPassword: string
  newPassword: string
}

export type RegisterProps = {
  userType: string // "Member" | "Institution" | "State" | "Zonal"
  fullname: string
  email: string
  password: string
}

export type CustomInputProps<T> = {
  // IconLeft?: IconType
  // IconRight?: IconType
  iconLeft?: boolean
  iconRight?: boolean
  name: Path<T>
  label?: string
  placeholder?: string
  required?: boolean
  register: UseFormRegister<T>
  customStyle?: string
  // errors?: FieldErrors | undefined
} & ComponentProps<"input">

export type FeedbackCardProps = {
  user: {
    imageUrl: string
    name: string
    institution: string
  }
  comment: string
}

export type CustomTabProps = {
  title: string
  tabChildren: JSX.Element[]
}

// institution profile
export type InstitutionProfileData = {
  acronym: string
  address: string
  lat: number
  long: number
  state: string
  zone:  "SOUTH_WEST"| "NORTH_WEST" | "NORTH_CENTRAL" | "NORTH_EAST"
  email: string
  phoneNumber: string
  avatarUrl?: string
  stateProfileId: string
  institutionName: "UNIVERSITY_OF_ABUJA"|"FEDERAL_COLLEGE_OF_EDUCATION_ZUBA"|"KOGI_STATE_UNIVERSITY"|"KOGI_STATE_POLYTECHNIC"|"FEDERAL_UNIVERSITY_LOKOGA"|"FEDERAL_POLYTECHNIC_IDAH"|"COLLEGE_OF_HEALTH_SCIENCE_AND_TECHNOLOGY_IDAH"|"UNIVERSITY_OF_ILORIN"|"KWARA_STATE_UNIVERSITY_MOLETE"|"COLLEGE_OF_EDUCATION_ILORIN"|"COLLEGE_OF_EDUCATION_ORO"|"FEDERAL_POLYTECHNIC_OFFA"|"KWARA_STATE_POLYTECHNIC_ILORIN"|"KWARA_STATE_COLLEGE_OF_HEALTH_TECHNOLOGY_OFFA"|"COLLEGE_OF_EDUCATION_LAFIA_AJI"|"FEDERAL_UNIVERSITY_LAFIA"|"FEDERAL_POLYTECHNIC_NASSARAWA"|"COLLEGE_OF_AGRICULTURE_LAFIA"|"SCHOOL_OF_HEALTH_KEFFI"|"COLLEGE_OF_EDUCATION_AKWANGA"|"NASSARAWA_STATE_UNIVERSITY_KEFFI"|"ISA_MUSTAPHA_AGWAEI_POLYTECHNIC_LAFIA"|"FEDERAL_UNIVERSITY_OF_TECHNOLOGY_MINNA"|"IBRAHIM_BADAMASI_BABANGIDA_UNIVERSITY_LAPAI"|"FCE_KONTONGORA"|"MODIBBO_ADAMA_UNIVERSITY_OF_TECHNOLOGY_YOLA"|"FCE_YOLA"|"COLLEGE_FOR_LEGAL_STUDIES_YOLA"|"ADAMAWA_STATE_UNIVERSITY_MUBI"|"ADAMAWA_STATE_POLYTECHNIC_YOLA"|"FEDERAL_POLY_MUBI"|"COLLEGE_OF_AGRIC_GANYE"|"COLLEGE_OF_HEALTH_TECH_MUBI"|"KANZUL_ISLAM_ACADEMY_YOLA"|"SCHOOL_FOR_ARABIC_AND_ISLAMIC_STUDIES_YOLA"|"ABUBAKAR_TAFAWA_BALEWA_UNIVERSITY"|"BAUCHI_STATE_UNIVERSITY_GADAU"|"BILL_AND_MELINDA_COLLEGE_OF_HEALTH_TECHNOLOGY_NINGI"|"AMINU_SALE_COLLEGE_OF_EDUCATION_AZARE"|"AD_RUFAI_COLLEGE_OF_EDUCATION"|"LEGAL_AND_GENERAL_STUDIES_MISAU"|"ADAMU_TAFAWA_BALEWA_COLLEGE_OF_EDUCATION_KANGERE"|"BILYAMINU_USMAN_COLLEGE_OF_EDUCATION_DASS"|"COLLEGE_OF_AGRICULTURE_BAUCHI"|"UNIVERSITY_OF_MAIDUGURI"|"RAMAT_POLYTECHNIC"|"KASHIM_IBRAHIM_COLLEGE_OF_EDUCATION"|"MUHAMMAD_GONI_COLLEGE_OF_LEGAL_AND_ISLAMIC_STUDIES"|"FEDERAL_UNIVERSITY_KASHERE"|"GOMBE_STATE_UNIVERSITY"|"FEDERAL_COLLEGE_OF_EDUCATION"|"SCHOOL_OF_LEGAL_AND_ISLAMIC_STUDIES_NAFADA"|"COE_BILLIRI"|"HEALTH_TECHNOLOGY_KALTUNGO"|"FEDERAL_COLLEGE_OF_HORTICULTURE_DADIN_KOWA_GOMBE"|"TARABA_STATE_UNIVERSITY"|"YOBE_STATE_UNIVERSITY"|"SULE_LAMIDO_UNIVERSITY"|"JIGAWA_STATE_COLLEGE_OF_EDUCATION_GUMEL"|"FEDERAL_UNIVERSITY_DUTSE"|"HUSSAINI_ADAMU_FEDERAL_POLYTECHNIC_HADEJA"|"NCE_RINGIM"|"JIGAWA_STATE_POLYTECHNIC"|"AHMADU_BELLO_UNIVERSITY_ZARIA"|"KADUNA_STATE_UNIVERSITY"|"KADUNA_STATE_POLYTECHNIC"|"NUHU_BAMALI_POLYTECHNIC_ZARIA"|"FEDERAL_COLLEGE_OF_EDUCATION_ZARIA"|"DIVISION_OF_AGRICULTURE_ABU_ZARIA"|"FEDERAL_COOPERATIVE_COLLEGE_KADUNA"|"COLLEGE_OF_HEALTH_SCIENCE_AND_TECHNOLOGY_MAKARFI"|"SCHOOL_OF_BASIC_AND_REMEDIAL_STUDIES_ABU"|"SCHOOL_OF_NURSING_ABU_TEACHING_HOSPITAL_TUDUN_WADA"|"BAYERO_UNIVERSITY_KANO"|"KANO_UNIVERSITY_OF_SCIENCE_AND_TECHNOLOGY_WUDIL"|"FEDERAL_COLLEGE_OF_EDUCATION_BICHI"|"MAITAMA_SULE_UNIVERSITY"|"FEDERAL_COLLEGE_OF_EDUCATION_KANO"|"UMARU_MUSA_YARADUWA_UNIVERSITY_KATSINA"|"FEDERAL_UNIVERSITY_DUTSINMMA"|"ISAH_KAITA_COLLEGE_OF_EDUCATION"|"HASSAN_USMAN_POLYTECHNIC_KATSINA"|"FEDERAL_COLLEGE_OF_EDUCATION_KATSINA"|"SCHOOL_OF_HEALTH_TECHNOLOGY_KANKIYA"|"SCHOOL_OF_NURSING_KATSINA"|"YUSUF_BALA_USMAN_SCHOOL_OF_LEGAL_STUDIES_KATSINA"|"FEDERAL_UNIVERSITY_BIRNIN_KEBBI"|"KEBBI_STATE_UNIVERSITY_OF_SCIENCE_AND_TECHNOLOGY_ALIERU"|"WAZIRI_UMMARU_FEDERAL_POLYTECHNIC_BIRNIN_KEBBI"|"COLLEGE_OF_AGRICULTURE_ZURU"|"ADAMU_AUGI_COLLEGE_OF_EDUCATION_ARGUNGU"|"KEBBI_STATE_POLYTECHNIC_DAKINGARI"|"SCHOOL_OF_NURSING_BIRNIN_KEBBI"|"KEBBI_STATE_COLLEGE_OF_HEALTH_JEGA"|"USMANU_DANFODIYO_UNIVERSITY_SOKOTO"|"SOKOTO_STATE_UNIVERSITY"|"COLLEGE_OF_EDUCATION_SOKOTO"|"UMMARU_ALI_SHINKFI_POLYTECHNIC_SOKOTO"|"FEDERAL_UNIVERSITY_GUSAU"|"FEDERAL_POLYTECHNIC_KAURA_NAMDODA"|"FEDERAL_COLLEGE_OF_EDUCATION_TECHNICAL_GUSAU"|"COLLEGE_OF_EDUCATION_MARU"|"COLLEGE_OF_HEALTH_SCIENCE_AND_TECHNOLOGY_TSAFE"|"SCHOOL_OF_NURSING_AND_MIDWIFE_PRE_GUSAU"|"ABDU_GUSAU_POLYTECHNIC_TALATA_MAFARA"|"COLLEGE_OF_AGRICULTURE_AND_ANIMAL_SCIENCE_BAKURA"|"ZAMFARA_COLLEGE_OF_ART_AND_SCIENCE_GUSAU"|"EKITI_STATE_UNIVERSITY"|"FEDERAL_UNIVERSITY_OYE_EKITI"|"YABA_COLLEGE_OF_EDUCATION_YABA"|"ADENIRAN_OGUNSANYA_COLLEGE_OF_EDUCATION_IJANIKIN"|"UNIVERSITY_OF_LAGOS_AKOKA"|"LAGOS_STATE_POLYTECHNIC_IKORODU"|"LAGOS_STATE_COLLEGE_OF_HEALTH_AND_TECH_YABA"|"LAGOS_STATE_UNIVERSITY_OJO"|"FEDERAL_COLLEGE_OF_EDUCATION_AND_TECHNICAL_YABA"|"FEDERAL_POLYTECHNIC_ILARO"|"MOSHOOD_ABIOLA_POLYTECHNIC"|"OLABISI_ONABANJO_UNIVERSITY"|"FCE_OSIELE_ABEOKUTA"|"OGUN_STATE_INSTITUTE_OF_TECHNOLOGY_IGBESA"|"TAI_SHOLARIN_UNIVERSITY_OF_EDUCATION"|"FEDERAL_UNIVERSITY_OF_AGRICULTURE_ABEOKUTA"|"OGUN_STATE_COLLEGE_OF_HEALTH_TECHNOLOGY"|"FEDERAL_UNIVERSITY_OF_TECHNOLOGY_AKURE"|"ADEKUNLE_AJASIN_UNIVERSITY_AKUNGBA"|"ADEYEMI_UNIVERSITY"|"OBAFEMI_AWOLOWO_UNIVERSITY_ILE_IFE"|"OSUN_STATE_UNIVERSITY_OSOGBO"|"FEDERAL_POLYTECHNIC_EDE"|"OSUN_STATE_COLLEGE_OF_HEALTH_ILESHA"|"OSUN_STATE_COLLEGE_OF_EDUCATION_ILA_OROGUN"|"ASANUSIYAH_COLLEGE_ODE_OMU"|"OSUN_STATE_UNIVERSITY_OSOGBO_IKIRE_CAMPUS"|"UNIVERSITY_OF_IBADAN"|"OYO_STATE_COLLEGE_OF_HEALTH_SCIENCE_AND_TECH_ELEYELE_IBADAN"|"LADOKE_AKINTOLA_UNIVERSITY_OF_TECHNOLOGY_OGBOMOSHO"|"OYO_STATE_COLLEGE_OF_AGRICULTURE_AND_TECHNOLOGY_IGBOORA"|"EMMANUEL_ALAYANDE_COLLEGE_OF_EDUCATION_OYO"|"FEDERAL_COLLEGE_OF_AGRICULTURE_MOOR_PLANTATION"|"OKE_OGUN_POLYTECHNIC_SAKI"|"MUFUTAU_LANIHUN_COLLEGE_OF_EDUCATION_IBADAN"|"POLYTECHNIC_OF_IBADAN"
}